// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data_layer/data_source/models/user_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 2200544289145043451),
      name: 'UserEntity',
      lastPropertyId: const IdUid(5, 4056819852450164002),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7501889260845821708),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 3069599981077911343),
            name: 'userId',
            type: 9,
            flags: 2080,
            indexId: const IdUid(1, 291855382556817992)),
        ModelProperty(
            id: const IdUid(3, 2951737983575918413),
            name: 'token',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 3954081968452727204),
            name: 'expireTime',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 4056819852450164002),
            name: 'name',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 2200544289145043451),
      lastIndexId: const IdUid(1, 291855382556817992),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    UserEntity: EntityDefinition<UserEntity>(
        model: _entities[0],
        toOneRelations: (UserEntity object) => [],
        toManyRelations: (UserEntity object) => {},
        getId: (UserEntity object) => object.id,
        setId: (UserEntity object, int id) {
          object.id = id;
        },
        objectToFB: (UserEntity object, fb.Builder fbb) {
          final userIdOffset =
              object.userId == null ? null : fbb.writeString(object.userId!);
          final tokenOffset =
              object.token == null ? null : fbb.writeString(object.token!);
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          fbb.startTable(6);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, userIdOffset);
          fbb.addOffset(2, tokenOffset);
          fbb.addInt64(3, object.expireTime?.millisecondsSinceEpoch);
          fbb.addOffset(4, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final expireTimeValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final object = UserEntity(
              id: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 4),
              userId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              token: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8),
              expireTime: expireTimeValue == null
                  ? null
                  : DateTime.fromMillisecondsSinceEpoch(expireTimeValue),
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [UserEntity] entity fields to define ObjectBox queries.
class UserEntity_ {
  /// see [UserEntity.id]
  static final id =
      QueryIntegerProperty<UserEntity>(_entities[0].properties[0]);

  /// see [UserEntity.userId]
  static final userId =
      QueryStringProperty<UserEntity>(_entities[0].properties[1]);

  /// see [UserEntity.token]
  static final token =
      QueryStringProperty<UserEntity>(_entities[0].properties[2]);

  /// see [UserEntity.expireTime]
  static final expireTime =
      QueryIntegerProperty<UserEntity>(_entities[0].properties[3]);

  /// see [UserEntity.name]
  static final name =
      QueryStringProperty<UserEntity>(_entities[0].properties[4]);
}
